In [1]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

In [2]:
!pip install -q huggingface_hub datasets transformers

In [3]:
from huggingface_hub import login
from google.colab import userdata

login(token=userdata.get("HF_TOKEN"))

In [4]:
from datasets import load_dataset

dataset = load_dataset(
    "ainlpml/english-hindi",
    token=userdata.get("HF_TOKEN")
)

In [5]:
import pandas as pd
from pandas import DataFrame
df=DataFrame(dataset)
df.head()

                                               train
0  {'text': 'However, Paes, who was partnering Au...
1  {'text': 'Whosoever desires the reward of the ...
2  {'text': '"The value of insects in the biosphe...
3  {'text': 'Mithali To Anchor Indian Team Agains...
4  {'text': 'After the assent of the Honble Presi...

In [6]:
df.iloc[0:999]

                                                 train
0    {'text': 'However, Paes, who was partnering Au...
1    {'text': 'Whosoever desires the reward of the ...
2    {'text': '"The value of insects in the biosphe...
3    {'text': 'Mithali To Anchor Indian Team Agains...
4    {'text': 'After the assent of the Honble Presi...
..                                                 ...
994  {'text': '"The conference is being organized b...
995    {'text': 'All the BSE sectoral indices fell. '}
996  {'text': 'In such cases, we need to be cautiou...
997      {'text': 'Happy Birthday Sachin Tendulkar! '}
998  {'text': 'Ram Rahim rape case verdict: Punjab,...

[999 rows x 1 columns]

In [7]:
col = df.columns[0]

n = len(df) // 2

new_df = pd.DataFrame({
    "english": df[col].iloc[:n].reset_index(drop=True),
    "hindi": df[col].iloc[n:].reset_index(drop=True)
})

print(new_df.head())

                                             english  \
0  {'text': 'However, Paes, who was partnering Au...
1  {'text': 'Whosoever desires the reward of the ...
2  {'text': '"The value of insects in the biosphe...
3  {'text': 'Mithali To Anchor Indian Team Agains...
4  {'text': 'After the assent of the Honble Presi...

                                               hindi
0  {'text': 'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी...
1  {'text': 'और जो शख्स (अपने आमाल का) बदला दुनिय...
2  {'text': 'जैव-मंडल में कीड़ों का मूल्य बहुत है...
3  {'text': 'आस्ट्रेलिया के खिलाफ वनडे टीम की कमा...
4  {'text': '8 सितम्‍बर, 2016 को माननीय राष्‍ट्रप...

In [8]:
new_df.head()

,english,hindi
0,"{'text': 'However, Paes, who was partnering Au...",{'text': 'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी...
1,{'text': 'Whosoever desires the reward of the ...,{'text': 'और जो शख्स (अपने आमाल का) बदला दुनिय...
2,"{'text': '""The value of insects in the biosphe...",{'text': 'जैव-मंडल में कीड़ों का मूल्य बहुत है...
3,{'text': 'Mithali To Anchor Indian Team Agains...,{'text': 'आस्ट्रेलिया के खिलाफ वनडे टीम की कमा...
4,{'text': 'After the assent of the Honble Presi...,"{'text': '8 सितम्‍बर, 2016 को माननीय राष्‍ट्रप..."

In [9]:
(new_df.iloc[0][1])

/tmp/ipykernel_2244/2626317527.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  (new_df.iloc[0][1])

{'text': 'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था। '}

In [10]:
new_df["english"] = new_df["english"].apply(lambda x: x["text"])
new_df["hindi"] = new_df["hindi"].apply(lambda x: x["text"])

In [11]:
new_df["eng_word_count"] = new_df["english"].str.split().str.len()
new_df["hin_word_count"] = new_df["hindi"].str.split().str.len()

In [12]:
filtered_df = new_df[
    new_df["eng_word_count"].between(3, 60) &
    new_df["hin_word_count"].between(3, 60)
].reset_index(drop=True)

In [13]:
print(type(new_df.loc[0, "english"]))
print(new_df.loc[0, "english"])

<class 'str'>
However, Paes, who was partnering Australia's Paul Hanley, could only go as far as the quarterfinals where they lost to Bhupathi and Knowles

In [14]:

filtered_df = new_df[
    abs(new_df["eng_word_count"] - new_df["hin_word_count"]).between(-10,10)
].reset_index(drop=True)

In [15]:
new_df.head()
new_df.shape

(10000, 4)

In [16]:
new_df["eng_char_count"] = new_df["english"].str.len()
new_df["hin_char_count"] = new_df["hindi"].str.len()

In [17]:
new_df["diff_word_count"] = abs(new_df["eng_word_count"]-new_df["hin_word_count"])
new_df["diff_char_count"] = abs(new_df["eng_char_count"]-new_df["hin_char_count"])

In [18]:
new_df.head()

,english,hindi,eng_word_count,hin_word_count,eng_char_count,hin_char_count,diff_word_count,diff_char_count
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23,28,141,147,5,6
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26,35,141,155,9,14
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21,22,130,124,1,6
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9,9,56,48,0,8
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18,19,128,119,1,9

In [19]:
!pip install -q openpyxl

output_file = "cleaned_dataset.xlsx"

new_df.to_excel(output_file, index=False)

print(f"Dataset saved as: {output_file}")

Dataset saved as: cleaned_dataset.xlsx

Assignment 2

In [20]:
sample_df = new_df.iloc[:200].copy()
sample_df.head()

,english,hindi,eng_word_count,hin_word_count,eng_char_count,hin_char_count,diff_word_count,diff_char_count
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23,28,141,147,5,6
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26,35,141,155,9,14
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21,22,130,124,1,6
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9,9,56,48,0,8
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18,19,128,119,1,9

In [21]:
!pip install -q transformers sentencepiece sacremoses accelerate

In [22]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch

MODEL_NAME = "facebook/nllb-200-distilled-600M"
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
).to(device)

model.eval()
print(device)

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

cuda

In [23]:
import torch
from tqdm.auto import tqdm

src_lang, tgt_lang = "eng_Latn", "hin_Deva"
tokenizer.src_lang = src_lang
tgt_token_id = tokenizer.convert_tokens_to_ids(tgt_lang)

def translate_batch(texts, batch_size=16, max_length=256, num_beams=4):
    predictions = []
    for i in tqdm(range(0, len(texts), batch_size)):
        batch = texts[i:i + batch_size]
        inputs = tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length
        ).to(device)

        with torch.no_grad():
            generated = model.generate(
                **inputs,
                forced_bos_token_id=tgt_token_id,
                max_length=max_length,
                num_beams=num_beams
            )

        decoded = tokenizer.batch_decode(generated, skip_special_tokens=True)
        predictions.extend(decoded)
    return predictions

sample_df["predicted_hindi"] = translate_batch(sample_df["english"].tolist())
sample_df.head()

  0%|          | 0/13 [00:00<?, ?it/s]

,english,hindi,eng_word_count,hin_word_count,eng_char_count,hin_char_count,diff_word_count,diff_char_count,predicted_hindi
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23,28,141,147,5,6,"हालांकि, ऑस्ट्रेलिया के पॉल हैंली के साथ साझेद..."
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26,35,141,155,9,14,जो कोई सांसारिक बदला चाहता है तो अल्लाह के पास...
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21,22,130,124,1,6,"""बायोस्फीयर में कीड़ों का मूल्य बहुत बड़ा है क..."
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9,9,56,48,0,8,मिताली ने वनडे में ऑस्ट्रेलिया के खिलाफ भारतीय...
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18,19,128,119,1,9,"माननीय राष्ट्रपति की सहमति के बाद 8 सितंबर, 20..."

In [28]:
!pip install -q sacrebleu

import sacrebleu

refs = sample_df["hindi"].astype(str).tolist()
preds = sample_df["predicted_hindi"].astype(str).tolist()

# sacrebleu expects references as a list of lists (one list per reference set)
bleu = sacrebleu.corpus_bleu(preds, [refs])
chrf = sacrebleu.corpus_chrf(preds, [refs])
ter = sacrebleu.corpus_ter(preds, [refs])

results = (
    f"BLEU:  {bleu.score:.2f}\n"
    f"CHRF:  {chrf.score:.2f}\n"
    f"TER:   {ter.score:.2f}\n"
)

print(results)

with open("translation_metrics.txt", "w", encoding="utf-8") as f:
    f.write(results)

BLEU:  20.41
CHRF:  46.38
TER:   73.15

In [29]:
from google.colab import files

files.download("translation_metrics.txt")