In [2]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

In [3]:
!pip install -q huggingface_hub datasets transformers

ERROR: Operation cancelled by user

In [4]:
from huggingface_hub import login
from google.colab import userdata

login(token=userdata.get("HF_TOKEN"))

In [5]:
from datasets import load_dataset

dataset = load_dataset(
    "ainlpml/english-hindi",
    token=userdata.get("HF_TOKEN")
)

README.md:   0%|          | 0.00/86.0 [00:00<?, ?B/s]

eng.txt:   0%|          | 0.00/1.01M [00:00<?, ?B/s]

hin.txt:   0%|          | 0.00/2.45M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20000 [00:00<?, ? examples/s]

In [6]:
import pandas as pd
from pandas import DataFrame
df=DataFrame(dataset)
df.head()

                                               train
0  {'text': 'However, Paes, who was partnering Au...
1  {'text': 'Whosoever desires the reward of the ...
2  {'text': '"The value of insects in the biosphe...
3  {'text': 'Mithali To Anchor Indian Team Agains...
4  {'text': 'After the assent of the Honble Presi...

In [7]:
df.iloc[0:999]

                                                 train
0    {'text': 'However, Paes, who was partnering Au...
1    {'text': 'Whosoever desires the reward of the ...
2    {'text': '"The value of insects in the biosphe...
3    {'text': 'Mithali To Anchor Indian Team Agains...
4    {'text': 'After the assent of the Honble Presi...
..                                                 ...
994  {'text': '"The conference is being organized b...
995    {'text': 'All the BSE sectoral indices fell. '}
996  {'text': 'In such cases, we need to be cautiou...
997      {'text': 'Happy Birthday Sachin Tendulkar! '}
998  {'text': 'Ram Rahim rape case verdict: Punjab,...

[999 rows x 1 columns]

In [8]:
col = df.columns[0]

n = len(df) // 2

new_df = pd.DataFrame({
    "english": df[col].iloc[:n].reset_index(drop=True),
    "hindi": df[col].iloc[n:].reset_index(drop=True)
})

print(new_df.head())

                                             english  \
0  {'text': 'However, Paes, who was partnering Au...
1  {'text': 'Whosoever desires the reward of the ...
2  {'text': '"The value of insects in the biosphe...
3  {'text': 'Mithali To Anchor Indian Team Agains...
4  {'text': 'After the assent of the Honble Presi...

                                               hindi
0  {'text': 'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी...
1  {'text': 'और जो शख्स (अपने आमाल का) बदला दुनिय...
2  {'text': 'जैव-मंडल में कीड़ों का मूल्य बहुत है...
3  {'text': 'आस्ट्रेलिया के खिलाफ वनडे टीम की कमा...
4  {'text': '8 सितम्‍बर, 2016 को माननीय राष्‍ट्रप...

In [9]:
new_df.head()

,english,hindi
0,"{'text': 'However, Paes, who was partnering Au...",{'text': 'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी...
1,{'text': 'Whosoever desires the reward of the ...,{'text': 'और जो शख्स (अपने आमाल का) बदला दुनिय...
2,"{'text': '""The value of insects in the biosphe...",{'text': 'जैव-मंडल में कीड़ों का मूल्य बहुत है...
3,{'text': 'Mithali To Anchor Indian Team Agains...,{'text': 'आस्ट्रेलिया के खिलाफ वनडे टीम की कमा...
4,{'text': 'After the assent of the Honble Presi...,"{'text': '8 सितम्‍बर, 2016 को माननीय राष्‍ट्रप..."

In [10]:
(new_df.iloc[0][1])

/tmp/ipykernel_565/2626317527.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  (new_df.iloc[0][1])

{'text': 'आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाले पेस मियामी में क्वार्टरफाइनल तक ही पहुंच सके क्योंकि इस दौर में उन्हें भूपति और नोल्स ने हराया था। '}

In [11]:
new_df["english"] = new_df["english"].apply(lambda x: x["text"])
new_df["hindi"] = new_df["hindi"].apply(lambda x: x["text"])

In [12]:
new_df["eng_word_count"] = new_df["english"].str.split().str.len()
new_df["hin_word_count"] = new_df["hindi"].str.split().str.len()

In [13]:
filtered_df = new_df[
    new_df["eng_word_count"].between(3, 60) &
    new_df["hin_word_count"].between(3, 60)
].reset_index(drop=True)

In [14]:
print(type(new_df.loc[0, "english"]))
print(new_df.loc[0, "english"])

<class 'str'>
However, Paes, who was partnering Australia's Paul Hanley, could only go as far as the quarterfinals where they lost to Bhupathi and Knowles

In [15]:

filtered_df = new_df[
    abs(new_df["eng_word_count"] - new_df["hin_word_count"]).between(-10,10)
].reset_index(drop=True)

In [16]:
new_df.head()
new_df.shape

(10000, 4)

In [17]:
new_df["eng_char_count"] = new_df["english"].str.len()
new_df["hin_char_count"] = new_df["hindi"].str.len()

In [18]:
new_df["diff_word_count"] = abs(new_df["eng_word_count"]-new_df["hin_word_count"])
new_df["diff_char_count"] = abs(new_df["eng_char_count"]-new_df["hin_char_count"])

In [19]:
new_df.head()

,english,hindi,eng_word_count,hin_word_count,eng_char_count,hin_char_count,diff_word_count,diff_char_count
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23,28,141,147,5,6
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26,35,141,155,9,14
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21,22,130,124,1,6
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9,9,56,48,0,8
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18,19,128,119,1,9

In [20]:
!pip install -q openpyxl

output_file = "cleaned_dataset.xlsx"

new_df.to_excel(output_file, index=False)

print(f"Dataset saved as: {output_file}")

Dataset saved as: cleaned_dataset.xlsx